### ISSUE TITLE
Missing Sweet folder

### ISSUE THREAD

**Issue by TeddyBears** [nitsan-technologies/ns_helpdesk#1]
Hello,

IN the setup file there are lines to call Sweet Css and Js from EXT:ns_helpdesk/Resources/Public/Vendor/Sweet/ forlder. 
But this doesnot exist in your extension

I'm using TYPO3 10 and install the free version of the extension with composer

```
page {
    includeCSS {
        fontawsome = EXT:ns_helpdesk/Resources/Public/Css/font-awesome.css
        nshelpdeskmain = EXT:ns_helpdesk/Resources/Public/Css/ns-helpdesk.css
        nsconfigcss = EXT:ns_helpdesk/Resources/Public/Css/configuration.css
        sweet = EXT:ns_helpdesk/Resources/Public/Vendor/Sweet/sweetalert2.min.css
    }

    includeJSFooter {
        nshelpdeskmain = EXT:ns_helpdesk/Resources/Public/JavaScript/nshelpdesk.js
        nshelpdeskmain.defer = 1
        ckeditorjs = EXT:ns_helpdesk/Resources/Public/JavaScript/tinymce/tinymce.min.js
        ckeditorjs.defer = 1
        sweet = EXT:ns_helpdesk/Resources/Public/Vendor/Sweet/sweetalert2.all.min.js
    }
    ```

**Comment by nitsan-technologies** [comment]
Hello @TeddyBears 

Thanks for the prompt.

Yes, you are right. That file was not present, Actually, it's not in use so we have removed it from the setup file too.
You may now download the latest updated version of the extension with clean code.

Again, Thanks for the notification.

Thanks!
Team NITSAN
