### ISSUE TITLE
Unable to Close the Ticket!

### ISSUE THREAD

**Issue by Krishna-nitsan** [nitsan-technologies/ns_helpdesk#3]
Hello!

I'm checking this extension and found this issue,i am not able to close the ticket its showing some message,check the attachment!

Testing environment:
Typo3 V11.5.23
php v8.0
ns_helpdesk 2.1.0 

Please fix this !

Thanks!
![close_ticket_issue](https://user-images.githubusercontent.com/117087880/218470835-ba1fbe66-23f1-4281-b7b2-4d736d02509d.jpg)

**Comment by nitsan-technologies** [comment]
Hello @Krishna-nitsan,

Thank you for using our extension! We're happy to inform you that the issue has been resolved in the latest version of our extension.

If you are still experiencing this issue, please check if the default assignee is set correctly and ensure that jQuery is enabled.

Best regards,
Team @nitsan-technologies
